# 넘파이(numpy)

In [ ]:
# 필요한 라이브러리 import 필수
import numpy as np

#넘파이 배열과 파이썬 리스트 비교

In [ ]:
# 파이썬 리스트 자료 구조 데이터 생성
list_data = [1,2,3]
print(f'파이썬 리스트 {list_data}')

print('-'*80)

#넘파이 배열 생성
array_data = np.array(list_data)
print(f'넘파이 배열로 변환한 후 데이터: {array_data}')

파이썬 리스트 [1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열로 변환한 후 데이터: [1 2 3]

In [ ]:
# 파이썬 리스트와 넘파이 배열 차이점 확인

## 덧셈 연산

### 파이썬 리스트
result1 = list_data + list_data
print(f'파이썬 리스트에 대한 덧셈 연산의 결과: \n{result1}')

print('-'*80)

## 넘파이 배열
result2 = array_data + array_data
print(f'넘파이 배열에 대한 덧셈 연산의 결과: \n{result2}')
print('-'*80)
## 곱셈 연산

## 파이썬 리스트
result3 = list_data*3
print(f'파이썬 리스트에 대한 단순 곱셈 연산의 결과:{result3}')

## 함수를 이용한 파이썬 리스트 곱셈
result4 =[]
for num in list_data:
    result4.append(num*3)

print(f'파이썬 리스트에 대한 곱셈 연산의 결과: {result4}')

print('-'*80)

result5 = array_data*3
print(f'넘파이 배열에 대한 곱셈 연산의 결과: {result5}')

print('-'*80)

## 통계 처리 (평균값 구하기)

### 파이썬 리스트
list_average =sum(list_data) / len(list_data)
print(f'파이썬 리스트에 대한 평균값: {int(list_average)}')
print('-'*80)
### 넘파이 배열
array_average =array_data.mean()
print(f'넘파이 배열에 대한 평균 값 : {array_average}')

파이썬 리스트에 대한 덧셈 연산의 결과:
[1, 2, 3, 1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열에 대한 덧셈 연산의 결과:
[2 4 6]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 단순 곱셈 연산의 결과:[1, 2, 3, 1, 2, 3, 1, 2, 3]
파이썬 리스트에 대한 곱셈 연산의 결과: [3, 6, 9]
--------------------------------------------------------------------------------
넘파이 배열에 대한 곱셈 연산의 결과: [3 6 9]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 평균값: 2
--------------------------------------------------------------------------------
넘파이 배열에 대한 평균 값 : 2.0

In [ ]:
# 대괄호가 중첩된 리스트 자료 구조 생성
# 조건: 성분 원소의 갯수가 동일
list_data = ([[1,2,3],[1,2,3],[2,3,4]])
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 엑셀과 같은 표(table: 행과 열) 구조 형성-> 엑셀과 같은 표(talbe: 행과 열) 구조 생성
list_data = np.array([[1,2,3],[1,2,3],[2,3,4]])
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 배열한 결과: \n{list_data}')

# 2차원 배열 생성

In [ ]:
# 대괄호가 중첩된 리스트 자료 구조 생성
# 조건: 성분 원소의 갯수가 동일
list_data = ([[1,2,3],[1,2,3],[2,3,4]])
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 엑셀과 같은 표(table: 행과 열) 구조 형성-> 엑셀과 같은 표(talbe: 행과 열) 구조 생성
list_data = np.array([[1,2,3],[1,2,3]])
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 배열한 결과: \n{list_data}')

# 차원은 '데이터가 뻗어 나가는 방향(축)이 몇 개인가'라는 구조의 문제이고, 모양은 '그 방향마다 데이터가 구체적으로 몇 개씩 들어있는가'라는 크기의 문제
# 2차원 넘파이 - 2행 3열

대괄호가 중첩된 리스트 자료 구조 데이터 확인:
[[1, 2, 3], [1, 2, 3], [2, 3, 4]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 배열한 결과:
[[1 2 3]
 [1 2 3]]

# 인덱싱

In [ ]:
## 2차원 배열 인덱싱
## 파이썬 방식
## 1단계: 변수[인덱스] -> 첫번째 행 추출
arr = list_data
arr
print(arr[0])

print('-'*80)

## 2단계: 변수[인덱스] -> 첫 번쩨 행(첫 번째 성분원소)의 첫 번째 열 추출
#result2 = arr[0][0]
result2 = list_data[0][0]
print(result2)

print('-'*80)

## 넘파이 방식
## 배열과 차원 모양(2행/3열) 이용 -> 변수[행 인덱스, 열 인덱스]
import numpy as np
array_data = np.array([[1,2,3],[2,3,4]])
#array_data[행 인덱스, 열 인덱스]

print(f'숫자 1을 인덱싱한 결과: {result3}')

[1 2 3]
--------------------------------------------------------------------------------
1
--------------------------------------------------------------------------------
숫자 1을 인덱싱한 결과: 1

In [ ]:
# array_data[0,0] - 숫자 1의 자료형이자 np에서 사용하는 정수 + 64bit(용량 표현) = np.int64(1) = 주소를 지정한 것, 명령어를 내리지 않은 상태인 것
# 자료형을 표현할 때 쓰는건데 이렇게 출력하면 안됨 - 코랩에서만 작동하기 때문에 다른 코딩 프로그램에서는 출력이 안됨
# 파이썬의 공식 출력함수는 print이기 때문에 코랩의 출력방식에 익숙해지면 명령어가 없어서 나타나지 않음

# = 공식 함수 print를 써야 한다 !

# 넘파이 배열 연습 문제

In [ ]:
# 문제 1. 배열 생성 및 덧셈 연산
# 파이썬 리스트 [10, 20, 30]과 [1, 2, 3]을 각각 넘파이 배열로 생성하고, 두 배열을 더한 결과를
# 출력하는 코드를 작성하세요.

list1 = [10,20,30]
list2 = [1,2,3]

array1 = np.array(list1)
array2 = np.array(list2)

print(array1+array2)

# arr1 = np.array([10, 20, 30])
# arr2 = np.array([1, 2, 3])
# print(f'결과: {arr1 + arr2}')

[11 22 33]

In [ ]:
# 문제 2.  곱셈 연산
# 리스트 data = [5, 10, 15]의 모든 원소에 3을 곱한 결과를 얻고자 합니다. 넘파이 배열의 연산
# 특성을 이용하여 반복문 없이 결과를 출력하는 코드를 작성하세요.

data = [5, 10, 15]
result1 = np.array(data)*3
print(result1)
# data = [5, 10, 15]
# arr_data = np.array(data)
# multi = arr*3
# print(f'배열 곱셈 결과: {multi}')

[15 30 45]

In [ ]:
# 문제 3. 평균값 구하기
# 넘파이 배열 arr = np.array([10, 30, 50, 70, 90])의 평균값을 넘파이 전용 메서드를 사용하여
# 계산하고 출력하세요.

arr = np.array([10,30,50,70,90])
result2 =arr.mean()
print(result2)
# arr = np.array([10, 30, 50, 70, 90])
# average = arr.mean()
# print(f'평균값: {average}')

50.0

In [ ]:
# 문제 4. 2차원 배열 생성
# 리스트 [[10, 20], [30, 40]]를 넘파이 배열로 변환하여 2행 2열의 구조를 가진 배열을 생성하고
# 출력하세요.

# list3 = np.array([[10,20], [30,40]])

# result3 = list3[0,1]
# print(result3)
list_2d = [[10, 20], [30, 40]]
arr_2d = np.array(list_2d)
print(f'2차원 배열:\n{arr_2d}')

2차원 배열:
[[10 20]
 [30 40]]

In [ ]:
# 문제 5. 2차원 배열 인덱싱
# 문제 4에서 생성한 배열에서 숫자 40을 추출하고자 합니다. 넘파이의 구조(행, 열)를 이용한
# 인덱싱 방식(arr[행, 열])으로 코드를 작성하세요.

print(list3[1,1])
# 40은 1행 1열에 위치함 (인덱스는 0부터 시작)
# result = arr_2d[1, 1]
# print(f'추출된 숫자: {result}')

40

# 파이썬 복습 문제 30선

In [ ]:
# Part 1: 기초 다지기 (개념 조합 연습)
# 문제 1: 리스트와 f-string
# ● 자신이 좋아하는 음식 3가지를 리스트 foods에 담고, f-string을 이용해 "제가 가장 좋아하는
# 음식은 OOO입니다."라고 첫 번째 음식을 출력하세요.

love_food = ['떡볶이', '토마토', '햄버거']
print(f'제가 가장 좋아하는 음식은 {love_food[0]}입니다.')

제가 가장 좋아하는 음식은 떡볶이입니다.

In [ ]:
# 문제 2: 딕셔너리와 len()
# ● 책 정보를 담은 딕셔너리 book을 만들고 ('title', 'author', 'pages' 키 포함), .keys()를 이용해
# 이 책이 몇 개의 정보(key)로 이루어져 있는지 len()으로 계산하여 출력하세요.
# 예시)  book = {'title': '파이썬의 정석', 'author': '전문가', 'pages': 300}

book = {'title':'파이썬의 정석', 'author':'전문가','pages':300}
print(book.keys())
print(len(book.keys()))

dict_keys(['title', 'author', 'pages'])
3

In [ ]:
# 문제 3: 문자열 split()과 len()
# ● "오늘 점심 메뉴는 제육볶음입니다" 라는 문장을 sentence 변수에 저장하고, split()으로
# 단어 단위로 나눈 후, 총 몇 개의 단어로 이루어져 있는지 len()으로 출력하세요.

sentence = "오늘 점심 메뉴는 제육볶음입니다"
result = sentence.split(" ")

print(len(result))

4

In [ ]:
# 문제 4: 나머지 연산(%)과 if-else
# ● num 변수에 숫자를 하나 할당하고, 이 숫자가 5로 나누어 떨어지는지(% 사용) 판별하여
# "5의 배수입니다" 또는 "5의 배수가 아닙니다"를 출력하세요.

num = 99
if num % 5 == 0:
    print("5의 배수입니다")
else:
    print("5의 배수가 아닙니다")

5의 배수가 아닙니다

In [ ]:
# 문제 5: 빈 리스트와 append()
# ● my_numbers라는 빈 리스트를 만들고, append()를 세 번 사용하여 숫자 10, 20, 30을
# 추가한 뒤 최종 리스트를 출력하세요.

my_numbers = []
my_numbers.append(10)
my_numbers.append(20)
my_numbers.append(30)
print(my_numbers)

[10, 20, 30]

In [ ]:
# 문제 6: for문과 f-string
# ● 과일 이름이 담긴 fruits 리스트를 만들고, for문을 이용해 하나씩 꺼내 "맛있는 OOO"
# 형식으로 출력하세요.
# 예시: fruits = ['사과', '바나나', '딸기']

fruits = ['사과', '바나나', '딸기']

for fruits in fruits:
    print(f'맛있는 {fruits}')

맛있는 사과
맛있는 바나나
맛있는 딸기

In [ ]:
# 문제 7: 문자열 replace()와 lower()
# ● "I LOVE PYTHON" 이라는 문자열에서 'PYTHON'을 'CODING'으로 바꾼 뒤, 전체 문장을
# 소문자로 변경하여 출력하세요.

S = "I LOVE PYTHON"
S1= S.replace('PYTHON', 'CODING')
S2= S1.lower()
print(S2)

i love coding

In [ ]:
# 문제 8: 딕셔너리 값 수정과 f-string
# ● 내 정보 my_info 딕셔너리에 {'city': '서울'}을 할당한 후, 사는 도시를 '부산'으로 수정하고
# f-string으로 "제가 사는 도시는 부산입니다." 라고 출력하세요.
# 예시: my_info = {'city': '서울'}

my_info = {'city':'서울'}
my_info['city'] = '부산'
print(f'제가 사는 도시는 {my_info["city"]}입니다.')

제가 사는 도시는 부산입니다.

In [ ]:
# 문제 9: 문자열 strip()과 인덱싱
# ● " \n 파이썬 " 이라는 지저분한 문자열 dirty_string을 strip()으로 정리하고, 정리된 문자열의
# 첫 글자를 인덱싱으로 출력하세요.
dirty_string = " \n 파이썬 "
dirty_string = dirty_string.strip()
print(dirty_string[0])

파

In [ ]:
# 문제 10: 리스트 인덱싱과 사칙연산
# ● 숫자 리스트 data = [100, 200, 50]에서 첫 번째 원소와 두 번째 원소를 더한 값에서 세 번째
# 원소를 뺀 결과를 출력하세요.

data =[100,200,50]
result = data[0] + data[1] - data[2]
print(result)

250

In [ ]:
# Part 2: 응용력 키우기 (다중 개념 활용)

# 문제 11: 딕셔너리, 리스트 값, append()
# ● 사용자 프로필 profile 딕셔너리에 {'name': '김코딩', 'hobbies': ['영화보기']}를 만드세요. 그
# 다음 'hobbies' 리스트에 '독서'를 append()로 추가하고 profile 전체를 출력하세요.
# 예시: profile = {'name': '김코딩', 'hobbies': ['영화보기']}

profile = {'name': '김코딩', 'hobbies': ['영화보기']}
# profile['hobbies'].append('독서')
profile['hobbies'] = '독서'
print(profile)

{'name': '김코딩', 'hobbies': '독서'}

In [ ]:
# 문제 12: for문, if, 나머지 연산(%)
# ● numbers 리스트 [1, 2, 3, 4, 5, 6, 7, 8]를 for문으로 순회하면서, 짝수일 경우에만 "짝수:
# O"라고 출력하세요.

numbers = [1,2,3,4,5,6,7,8]
for numbers in numbers:
    if numbers % 2 == 0:
        print(f'짝수:0')

짝수:0
짝수:0
짝수:0
짝수:0

In [ ]:
# 문제 13: 문자열 strip(), split(), 인덱싱
# ● ",사과,바나나,포도," 형태의 문자열 data가 있습니다. 양쪽의 불필요한 ','를 strip(',')으로
# 제거하고, 다시 ,를 기준으로 split() 한 뒤, '바나나'를 인덱싱으로 출력하세요.
# 예시: data = ",사과,바나나,포도,"

data = ",사과,바나나,포도,"

data_re = data.strip(',')
date_rere = data_re.split(',')
print(date_rere[1])

사과,바나나,포도
바나나

In [ ]:
# 문제 14: for문과 if-elif-else
# ● scores 리스트 [88, 95, 72, 59, 100]를 for문으로 순회하며, 각 점수에 대해 90점 이상은 'A',
# 80점 이상은 'B', 70점 이상은 'C', 그 외는 'F' 등급을 출력하세요.
# 예시: scores = [88, 95, 72, 59, 100]

scores = [88,95,72,59,100]
for scores in scores:
    if scores >= 90:
        print('A')
    elif scores >= 80:
        print('B')
    elif scores >= 70:
        print('C')
    else:
        print('F')

B
A
C
F
A

In [ ]:
# 문제 15: 딕셔너리, for문, get()
# ● 상품 가격표 prices = {'사과': 1500, '바나나': 3000, '체리': 5000}와 구매 목록 wishlist =
# ['바나나', '사과', '딸기']가 있습니다. for문으로 wishlist를 순회하며, prices 딕셔너리에서
# .get()으로 가격을 찾아 출력하세요.
# 예시: prices = {'사과': 1500, '바나나': 3000, '체리': 5000}
# wishlist = ['바나나', '사과', '딸기']

prices = {'사과': 1500, '바나나': 3000, '체리': 5000}
wishlist = ['바나나', '사과', '딸기']

for item in wishlist:
    price = prices.get(item, '가격 정보 없음') # .get() 메서드에 키와 기본값 전달
    print(f'{item}의 가격: {price}')

바나나의 가격: 3000
사과의 가격: 1500
딸기의 가격: 가격 정보 없음

In [ ]:
# 문제 16: 리스트 join(), replace()
# ● ['Life', 'is', 'too', 'short'] 리스트를 join()으로 합쳐 하나의 문장으로 만드세요. 그 다음
# 'short'를 'long'으로 replace() 하여 최종 문장을 출력하세요.

list_data = ['Life', 'is', 'too', 'short']
sentence = ' '.join(list_data)
sentence = sentence.replace('short', 'long')
print(sentence)

Life is too long

In [ ]:
# 문제 17: 중첩 리스트와 인덱싱, f-string
# ● classes = [['철수', '영희'], ['민준', '서연']] 리스트에서 1반의 두 번째 학생 '영희'와 2반의 첫
# 번째 학생 '민준'을 각각 인덱싱하여 "스터디 파트너: 영희, 민준" 이라고 출력하세요.
# 예시: classes = [['철수', '영희'], ['민준', '서연']]

classes =[['철수','영희'], ['민준','서연']]

print(f'스터디 파트너: {classes[0][1]}, {classes[1][0]}')

스터디 파트너: 영희, 민준

In [ ]:
# 문제 18: for문, len(), 사칙연산 (총합 구하기)
# ● sales = [100, 150, 200, 120] 리스트의 총합을 for문을 이용해 구하세요. (총합을 저장할
# 변수 total을 0으로 시작)
# 예시:
sales = [100, 150, 200, 120]
total = 0

for sales in sales:
    total += sales
print(total)

570

In [ ]:
# 문제 19: 문자열 연결(+), len()
# ● first_name = "길동"  last_name = "홍" 두 변수를 만든 후, 두 변수를 합쳐 full_name을
# 만드세요. 그 후 full_name의 전체 글자 수가 3글자인지 if문과 len()으로 확인하여 맞으면
# "올바른 이름입니다", 아니면 "글자 수를 확인하세요"를 출력하세요.
first_name = "길동"
last_name = "홍"
full_name = first_name + last_name
if len(full_name) == 3:
    print('올바른 이름입니다')

올바른 이름입니다

In [ ]:
# 문제 20: 딕셔너리, .values(), for, if
# ● exam_results = {'철수': 85, '영희': 92, '민준': 76} 딕셔너리에서 .values()로 점수들만 추출한
# 뒤, for문으로 점수들을 확인하여 90점이 넘는 점수만 출력하세요.
# 예시:
exam_results = {'철수': 85, '영희': 92, '민준': 76}
score = exam_results.values()
for score in score:
    if score > 90:
        print(score)

92

In [ ]:
# Part 3: 종합 문제 해결 (프로젝트형 문제)

# 문제 21: 데이터 리스트 순회 및 필터링
# ● 여러 상품 정보가 담긴 products 리스트를 생성하세요(각자 자유롭게 만드시면 됩니다.) .
# products 리스트에 대해서 for문으로 리스트를 순회하며, 가격(price)이 20000원 이상인
# 상품의 이름(name)만 출력하세요.
# 예시:
products = [
{'name': '티셔츠', 'price': 15000},
{'name': '청바지', 'price': 25000},
{'name': '자켓', 'price': 50000}]

for products in products:
    if products['price'] >= 20000:
        print(products['name'])

청바지
자켓

In [ ]:
# 문제 22: 데이터 정제 및 새로운 리스트 생성
# ● raw_data = [' apple ', ' banana\n', ' \ncherry'] 리스트를 생성 후 각 과일 이름에 포함된
# 불필요한 공백과 줄바꿈 문자를 strip()으로 제거하고, 깨끗해진 과일 이름만
# clean_fruits라는 새 리스트에 append()하여 최종 결과를 출력하세요.
raw_data = [' apple ', ' banana\n', ' \ncherry']

clean_fruits = []
for item in raw_data:
    cleaned_item = item.strip().strip('\n')
     # strip()으로 공백 제거 후, 다시 strip('\n')으로 줄바꿈 문자 제거
    clean_fruits.append(cleaned_item)
print(clean_fruits)

['apple', 'banana', 'cherry']

In [ ]:
# 문제 23: 특정 문자 개수 세기
# ● sentence = "python is powerful and python is easy" 문장에서 for문을 이용해 알파벳 'p'가
# 총 몇 번 나타나는지 개수를 세어 출력하세요. (개수를 저장할 count 변수 활용)
# 예시: sentence = "python is powerful and python is easy"
# count = 0
sentence = "python is powerful and python is easy"
count = 0
for sentence in sentence:
    if sentence == 'p':
        count += 1

print(count)

3

In [ ]:
# 문제 24: 회원 등급 자동 부여

# ● users 리스트에는 회원들의 구매 횟수(visits) 정보가 담겨 있습니다. for문으로 각 회원을
# 확인하고, 구매 횟수가 10회 이상이면 grade를 'VIP'로, 5회 이상이면 'Gold'로, 그 외는
# 'Silver'로 users 딕셔너리에 새로운 키-값 쌍을 추가한 뒤, 전체 users 리스트를 출력하세요.
users = [
{'id': 'user1', 'visits': 12},
{'id': 'user2', 'visits': 3},
{'id': 'user3', 'visits': 7} ]

for user in users:
    if user['visits'] >= 10:
        user['grade'] = 'VIP'
    elif user['visits'] >= 5:
        user['grade'] = 'Gold'
    else:
        user['grade'] = 'Silver'
print(users)

[{'id': 'user1', 'visits': 12, 'grade': 'VIP'}, {'id': 'user2', 'visits': 3, 'grade': 'Silver'}, {'id': 'user3', 'visits': 7, 'grade': 'Gold'}]

In [ ]:
# 문제 25: 쇼핑 카트 총액 계산
# ● 가격 정보가 담긴 menu 딕셔너리와 내가 담은 my_cart 리스트가 있습니다. for문을 이용해
# my_cart에 담긴 상품들의 총 가격을 계산하여 출력하세요.
# 예시:
menu = {'아메리카노': 3000, '라떼': 3500, '케이크': 5000}
my_cart = ['아메리카노', '아메리카노', '케이크']
total = 0 # Initialize total as an integer
for item in my_cart:
    total += menu[item]

print(total)

11000

In [ ]:
# 문제 26: 파일명 일괄 변경 시뮬레이션
# ● files = ['report_ver1.docx', 'image_ver1.jpg', 'data_ver1.csv'] 리스트가 있습니다. for문을
# 이용해 각 파일명의 'ver1' 부분을 'ver2'로 replace()하여 새로운 파일명 리스트 new_files를
# 만들어 출력하세요.
# 예시: files = ['report_ver1.docx', 'image_ver1.jpg', 'data_ver1.csv']

files = ['report_ver1.docx', 'image_ver1.jpg', 'data_ver1.csv']
for files in files:
    new_files = files.replace('ver1', 'ver2')
    print(new_files)

report_ver2.docx
image_ver2.jpg
data_ver2.csv

In [ ]:
# 문제 27: 이메일 주소에서 아이디만 추출하기
# ● 이메일 주소 리스트 emails가 있습니다. 각 이메일 주소에서 @를 기준으로 split()하여
# 아이디 부분만 user_ids라는 새 리스트에 담아 출력하세요.

emails = ['python@google.com', 'java@oracle.com', 'swift@apple.com']
user_ids = []
for email in emails:
    # email.split('@')는 '@'를 기준으로 문자열을 나누어 리스트를 반환합니다.
    # 예를 들어 'python@google.com'에 대해 ['python', 'google.com']을 반환합니다.
    # [0]은 이 리스트의 첫 번째 요소, 즉 아이디 부분을 선택합니다.
    user_ids.append(email.split('@')[0])
print(user_ids)

# 이해를 돕기 위해 예시를 추가합니다:
# email_example = 'test@example.com'
# print(f"'{email_example}'.split('@') 결과: {email_example.split('@')}")
# print(f"첫 번째 요소 (아이디): {email_example.split('@')[0]}")
# email.split('@')`는 이메일 문자열을 `@` 앞부분과 뒤부분, 이렇게 두 부분으로 이루어진 리스트로 분리합니다.
# 예를 들어, '[redacted link]'의 경우 `email.split('@')`는 `['python', 'google.com']`을 반환합니다.
# 우리는 이 리스트의 첫 번째 요소인 사용자 이름을 얻으려고 하므로 `[0]`을 사용하여 접근합니다.

['python', 'java', 'swift']

In [ ]:
# 문제 28: 문자열 데이터를 딕셔너리로 변환
# ● "name:김철수,age:30,city:서울" 형태의 문자열 user_data가 있습니다. 이 문자열을
# split()과 for문을 활용하여 {'name': '김철수', 'age': '30', 'city': '서울'} 형태의 딕셔너리로
# 만들어 출력하세요.
user_data = "name:김철수,age:30,city:서울"
dic_data = {}

# 먼저 콤마(,)를 기준으로 문자열을 분리하여 각 '키:값' 쌍을 얻습니다.
pairs = user_data.split(',')

# 각 쌍을 순회하며 콜론(:)을 기준으로 다시 분리하여 키와 값을 추출하고 딕셔너리에 추가합니다.
for pair in pairs:
    key, value = pair.split(':') # '키:값' 문자열을 콜론을 기준으로 분리
    dic_data[key] = value

print(dic_data)

{'name': '김철수', 'age': '30', 'city': '서울'}

In [ ]:
# 문제 29: 대소문자 섞인 데이터 정규화
# ● tags = [' Python', 'JAVA ', ' \nRuby', 'python'] 리스트에 정리되지 않은 태그들이 있습니다.
# for문으로 각 태그의 공백을 strip()으로 제거하고, lower()로 모두 소문자로 바꾼 뒤,
# clean_tags 리스트에 append()하여 clean_tags 전체를 출력하세요.
# 예시: tags = ['  Python', 'JAVA  ', ' \nRuby', 'python']

tags = ['  Python', 'JAVA  ', ' \nRuby', 'python']
clean_tags = []
for tag in tags:
    clean_tags.append(tag.strip().lower())
    print(clean_tags)

['python']
['python', 'java']
['python', 'java', 'ruby']
['python', 'java', 'ruby', 'python']

In [ ]:
# 문제 30: 학생 평균 점수 및 등급 계산기 (최종 종합 문제)
# ● 학생들의 이름과 점수 리스트가 담긴 students 데이터가 있습니다. for문으로 각 학생을
# 순회하며 다음을 수행하세요:
# 1. 학생의 점수 리스트의 총합과 평균을 계산합니다. (총합/len())
# 2. 계산된 평균 점수를 기준으로 if-elif-else를 사용하여 등급('A', 'B', 'C')을 부여합니다.
# (90점 이상 'A', 80점 이상 'B', 나머지 'C')
# 3. 최종적으로 "OOO 학생 / 평균: XX.X점 / 등급: O" 형식으로 출력합니다.
# 예시:
students = [
{'name': '김철수', 'scores': [95, 88, 91]},
{'name': '이영희', 'scores': [82, 85, 80]},
{'name': '박민준', 'scores': [75, 71, 78]}
]
for student in students:
 scores = student['scores']
 name = student['name']
# 1. 총합과 평균 계산
 total_score = 0
 for score in scores:
  total_score = total_score + score
 avg_score = total_score / len(scores)
# 2. 등급 부여
 grade = ''
 if avg_score >= 90:
  grade = 'A'
 elif avg_score >= 80:
  grade = 'B'
 else:
  grade = 'C'
# 3. 최종 결과 출력
 print(f"{name} 학생 / 평균: {int(avg_score)}점 / 등급: {grade}")

# for student in students:
#     scores = student['scores']
#     name = student['name']

#     total_score = sum(scores)
#     average = total_score / len(scores)

#     # 학생 딕셔너리에 평균과 등급 추가
#     student['total'] = total_score
#     student['average'] = average

#     if average >= 90:
#         student['grade'] = 'A'
#     elif average >= 80:
#         student['grade'] = 'B'
#     else:
#         student['grade'] = 'C'

#     # 최종 출력
#     print(f"{student['name']} 학생 / 평균: {student['average']:.1f}점 / 등급: {student['grade']}")

김철수 학생 / 평균: 91점 / 등급: A
이영희 학생 / 평균: 82점 / 등급: B
박민준 학생 / 평균: 74점 / 등급: C

# 파이썬 전단원 연습문제 2

In [ ]:
# 1. 다음과 같은 코드 실행의 결과로 알맞은 것은?

# week = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
# today = week[2]

# print(today)

In [ ]:

# 2. box = "apple"의 뜻은?
# 1) box 변수의 이름은 apple이다.
# 2) box 변수에 문자열 데이터 apple를 저장하라
# 3) box 변수와 apple은 같다.
# 4) box 변수는 apple이다.

In [ ]:


# 3. 다음과 같이 코드를 작성했을 때, 실행 결과는?

# print(53 % 10)

In [ ]:

# 4. 다음 코드의 실행결과는?

# a = 572
# print (type(a))

In [ ]:

# 5. 다음과 같이 코드를 작성했을 때, 실행 결과로 알맞은 것은?

# list_data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# number = len(list_data)

# print(number)

In [ ]:

# 6. 다음과 같이 코드를 작성했을 때, 실행 결과로 알맞은 것은?

# fruit1 = ['orange','melon','strawberry']
# fruit2 = 'watermelon'

# fruit1.append(fruit2)

# print(fruit1)

In [ ]:

# 7. 다음과 같이 코드를 작성했을 때, 실행 결과는? 정답 : 11
# a = [1, 2, 3, 5]
# b = ['a', 'b', 'c','d','e']

# a.append('g')
# b.append(6)

# print(len(a) + len(b))

In [ ]:

# 8. 다음과 같이 코드를 작성했을 때, 실행 결과는? 정답 : [10, 20, 30, 40, 50, 100], [10, 20, 30, 40, 50, 100, 1000]

# our_list = [10, 20, 30, 40, 50]
# our_list.append(100)
# print(our_list)

# our_list.append(1000)
# print(our_list)

In [ ]:

# 9. [주관식] 함수를 정의할 때 가장 처음에 사용하는 예약어는?

# def
# = def는 코드 덩어리를 묶어 함수로 만들어내는 역할

In [ ]:

# 10. 다음 코드의 실행 결과는?

# # 변수 설정
# money = 1200

# # 조건문 실행
# if money>=15000:
#     print('택시를 탄다')
# elif 15000>money>=3000:
#     print('광역 버스를 탄다')
# elif 3000>money>=1500:
#     print('지하철을 탄다')
# else:
#     print('걸어간다')

In [ ]:

# 11. 다음과 같이 코드를 작성했을 때, 실행 결과는?

# def print_hi():
#     print("Hi")

In [ ]:

# 12. 다음 코드의 실행 결과는? 정답 : 정답 : ab

# a = 11
# b = 9

# print('a' + 'b')

In [ ]:

# 13. 다음과 같이 코드를 작성했을 때, 실행 결과는?

# number = 10
# day = 3
# print(f"I eat {number} oranges every day.")

In [ ]:

# 14. 다음 문자열 함수 중 설명이 잘못된 것을 고르시오. 정답 : 3)
# 1) split() : 입력한 문자를 기준으로 문자열을 분리하여 리스트로 출력
# 2) join() : 리스트의 형태로 분리된 문자열을 입력한 문자를 기준으로 연결
# 3) strip() : 공백을 기준으로 나눠 리스트를 반환한다.
# 4) lower() : 문자열을 소문자로 변환한다.


# strip: 문자열 및 공백 제거

In [ ]:

# 15. 다음과 같이 코드를 작성했을 때, 실행 결과는?
# fruits = ('apple','banana','cherry','strawberry')
# fruits[0] = 'orange'

# fruits = 'orange', 'banana', 'cherry', 'strawberry'

In [4]:

# # # 16. 다음과 같이 코드를 작성했을 때, 실행 결과는?
# # colors = ['orange', 'pink', 'brown', 'black', 'white', 'yellow']
# # result = '&'.join(colors)
# # print(result)

# orange&pink&brown&black&white&yellow

orange&pink&brown&black&white&yellow

In [5]:

# # 17. 다음과 같이 코드를 작성했을 때, 실행 결과는?

# test_data = 3

# def multiply(a):
#     b = a*3
#     return b

# print(multiply(test_data))

# multiplay의 a값이 test_data의 3으로 등록됨
# b의 값을 return하는 것이므로 3*3 값이 출력됨

Object `결과는` not found.
9

In [ ]:

# 18. 파이썬에서 특수문자 '\n'은 어떤 기능을 가지고 있는지 고르시오
# 1) Tab키
# 2) 백스페이스
# 3) 줄바꾸기
# 4) Esc키
#답: 3

In [ ]:
# 19. 다음과 같이 코드를 작성했을 때, 실행 결과는?

# list_data = [3, 2, 1, 4]
# del list_data[0]

# print(list_data)
# list_data = [2,1,4]

In [ ]:
# 20. 다음과 같이 코드를 작성했을 때, 실행 결과는?

# def test(k):
#     print(f"Input is {k}")

# k = 100
# test(k)
# 정답: Input is 100

In [ ]:
# 21. 다음 중 파이썬의 변수명으로 적절치 않은 것은?
# 1) ABC1982
# 2) abc1982
# 3) 1982abc
# 4) abc_23

# 정답: 3

# 판다스(pandas)

In [ ]:
# 필요한 라이브러리 임포트
import pandas as pd

## DataFrame 자료 구조 생성: csv 파일 처리

In [ ]:
# colab과 구글 드라이브 연결

In [ ]:
# 다른사람의 코드를 가져와서 쓸때에도 이렇게 뜰 수 있음
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# DataFrame 생성

## 파일 경로(위치) 설정
# colab의 경우 경로복사가 존재, 윈도우도 마찬가지로 경로로 복사가 존재함
file_path = "/content/drive/MyDrive/KDT/ad_performance.csv"

# df = pd.read_csv(file_path) 호출
df = pd.read_csv(file_path)

# 결과 확인 - print는 코랩에서만 제공하는 기능
print(df)
# display는 데이터프레임 전용
display(df)

            Date   Channel Age_Group  Gender  Impressions  Clicks    Cost  \
0     2025-01-01  Facebook      50s+    Male        15412     578  100308
1     2025-01-01    Google       20s    Male        11990     897  103029
2     2025-01-01     Naver      50s+  Female        18503     471  158046
3     2025-01-01   Organic       30s  Female         6866     686   81358
4     2025-01-01     Naver       30s    Male         5250     525  295050
...          ...       ...       ...     ...          ...     ...     ...
4995  2025-06-29   Organic       20s  Female        10064     933  180066
4996  2025-06-29     Naver       40s    Male         5657     537   71261
4997  2025-06-29   Organic       40s    Male         7331     378  159162
4998  2025-06-29    Google       20s    Male         9272     124  173437
4999  2025-06-29     Naver       30s  Female        12688     733  193294

      Conversions  Revenue
0              27   723225
1              26  1680444
2              48  1580303
3              28   520546
4              23  1505721
...           ...      ...
4995           40   814096
4996            7   256452
4997           20   795243
4998           23  1293372
4999           13  1000870

[5000 rows x 9 columns]

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

## 분헤

In [ ]:
# 행 인덱스 추출
info_index = df.index
print(f' DataFrame의 행 인덱스: {info_index}')

print('-'*80)

# 컬럼 인덱스 추출
info_columns = df.columns
print(f'(DataFrame의 컬럼 인덱스: \n{info_columns}')

print('-'*80)

# 값 추출
info_values = df.values
print(f'DataFrame의 값: \n{info_values}')

 DataFrame의 행 인덱스: RangeIndex(start=0, stop=5000, step=1)
--------------------------------------------------------------------------------
(DataFrame의 컬럼 인덱스:
Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='object')
--------------------------------------------------------------------------------
DataFrame의 값:
[['2025-01-01' 'Facebook' '50s+' ... 100308 27 723225]
 ['2025-01-01' 'Google' '20s' ... 103029 26 1680444]
 ['2025-01-01' 'Naver' '50s+' ... 158046 48 1580303]
 ...
 ['2025-06-29' 'Organic' '40s' ... 159162 20 795243]
 ['2025-06-29' 'Google' '20s' ... 173437 23 1293372]
 ['2025-06-29' 'Naver' '30s' ... 193294 13 1000870]]

## 인덱싱

In [ ]:
# 특정 컬럼 인덱싱
cl = df['Channel']
print(cl)

0       Facebook
1         Google
2          Naver
3        Organic
4          Naver
          ...
4995     Organic
4996       Naver
4997     Organic
4998      Google
4999       Naver
Name: Channel, Length: 5000, dtype: object

In [ ]:
#fancy 인덱싱: 변수[['컬럼1','컬럼4','컬럼3'----]]

df1=df[['Channel','Clicks','Revenue']]

#print(df1)
display(df1)

       Channel  Clicks  Revenue
0     Facebook     578   723225
1       Google     897  1680444
2        Naver     471  1580303
3      Organic     686   520546
4        Naver     525  1505721
...        ...     ...      ...
4995   Organic     933   814096
4996     Naver     537   256452
4997   Organic     378   795243
4998    Google     124  1293372
4999     Naver     733  1000870

[5000 rows x 3 columns]

In [ ]:
print(df['Clicks'])
print('-'*80)
print(df['Impressions'])

0       578
1       897
2       471
3       686
4       525
       ...
4995    933
4996    537
4997    378
4998    124
4999    733
Name: Clicks, Length: 5000, dtype: int64
--------------------------------------------------------------------------------
0       15412
1       11990
2       18503
3        6866
4        5250
        ...
4995    10064
4996     5657
4997     7331
4998     9272
4999    12688
Name: Impressions, Length: 5000, dtype: int64